/**
 * @generated
 * @file ToggleButton (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import NotSupported from "../webflow_modules/Builtin/components/NotSupported";

/**
 * Props for {@link ToggleButton}
 *
 * A styled toggle button. Use the same Group Name to enforce single-selection across buttons.
 */
export type ToggleButtonProps = {
  groupName?: string;
  label?: string;
  offStateBackgroundOff?: string;
  offStateFontColorOff?: string;
  onStateBackgroundOn?: string;
  onStateFontColorOn?: string;
  typographyFontFamily?: string;
  typographyFontWeight?: string;
};

/**
 * ToggleButton
 *
 * A styled toggle button. Use the same Group Name to enforce single-selection across buttons.
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
export function ToggleButton({}: ToggleButtonProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <NotSupported _atom={"Code Island"} />
    </div>
  );
}
