/**
 * @generated
 * @file ToggleGroup (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import NotSupported from "../webflow_modules/Builtin/components/NotSupported";

/**
 * Props for {@link ToggleGroup}
 *
 * Wrapper for Toggle Buttons — enforces single-selection. Outputs the active button's label as data-selected.
 */
export type ToggleGroupProps = {
  direction?: "Horizontal" | "Vertical";
  groupName?: string;
  layoutGapRem?: string;
  numberOfButtons?: "2" | "3" | "4" | "5" | "6" | "7" | "8";
  slotsButton1?: React.ReactNode;
  slotsButton2?: React.ReactNode;
  slotsButton3?: React.ReactNode;
  slotsButton4?: React.ReactNode;
  slotsButton5?: React.ReactNode;
  slotsButton6?: React.ReactNode;
  slotsButton7?: React.ReactNode;
  slotsButton8?: React.ReactNode;
  spacingPaddingBlockRem?: string;
  spacingPaddingInlineRem?: string;
  targetId?: string;
};

/**
 * ToggleGroup
 *
 * Wrapper for Toggle Buttons — enforces single-selection. Outputs the active button's label as data-selected.
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
export function ToggleGroup({}: ToggleGroupProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <NotSupported _atom={"Code Island"}>
        {slotsButton1}
        {slotsButton2}
        {slotsButton3}
        {slotsButton4}
        {slotsButton5}
        {slotsButton6}
        {slotsButton7}
        {slotsButton8}
      </NotSupported>
    </div>
  );
}
