/**
 * @generated
 * @file TriggerButton (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import NotSupported from "../webflow_modules/Builtin/components/NotSupported";

/**
 * Props for {@link TriggerButton}
 *
 * A toggle button that controls visibility of page elements. Add data-target={{ID}} & data-hide={{toggle-on|toggle-off}} attributes to target elements.
 */
export type TriggerButtonProps = {
  groupGroupName?: string;
  label?: string;
  offStateBackgroundOff?: string;
  offStateFontColorOff?: string;
  onStateBackgroundOn?: string;
  onStateFontColorOn?: string;
  triggerId?: string;
  typographyFontFamily?: string;
  typographyFontWeight?: string;
};

/**
 * TriggerButton
 *
 * A toggle button that controls visibility of page elements. Add data-target={{ID}} & data-hide={{toggle-on|toggle-off}} attributes to target elements.
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
export function TriggerButton({}: TriggerButtonProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <NotSupported _atom={"Code Island"} />
    </div>
  );
}
