/**
 * @generated
 * @file ColorPicker (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import NotSupported from "../webflow_modules/Builtin/components/NotSupported";

/**
 * Props for {@link ColorPicker}
 *
 * A popup swatch color picker. Click the trigger square to open. Outputs selected hex to data-color.
 */
export type ColorPickerProps = {
  layoutSwatchSize?: string;
  layoutTriggerSize?: string;
};

/**
 * ColorPicker
 *
 * A popup swatch color picker. Click the trigger square to open. Outputs selected hex to data-color.
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
export function ColorPicker({}: ColorPickerProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <NotSupported _atom={"Code Island"} />
    </div>
  );
}
