/**
 * @generated
 * @file DateInput (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import NotSupported from "../webflow_modules/Builtin/components/NotSupported";

/**
 * Props for {@link DateInput}
 *
 * A segmented date input (MM/DD/YY) that outputs data-date in yyyy-MM-dd format.
 */
export type DateInputProps = {
  colorsBackground?: string;
  colorsBorderColor?: string;
  colorsFocusColor?: string;
  colorsSeparatorColor?: string;
  colorsTextColor?: string;
  typographyFontFamily?: string;
  typographyFontSize?: string;
  typographyFontWeight?: string;
};

/**
 * DateInput
 *
 * A segmented date input (MM/DD/YY) that outputs data-date in yyyy-MM-dd format.
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
export function DateInput({}: DateInputProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <NotSupported _atom={"Code Island"} />
    </div>
  );
}
