/**
 * @generated
 * @file NumberStepper (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import NotSupported from "../webflow_modules/Builtin/components/NotSupported";

/**
 * Props for {@link NumberStepper}
 *
 * A date-aware stepper. Pick Week/Month/Quarter/Year to auto-calculate dates, or Custom to hide. Outputs data-date (yyyy-MM-dd) and data-value.
 */
export type NumberStepperProps = {
  colorsBackground?: string;
  colorsBorderColor?: string;
  colorsButtonBackground?: string;
  colorsButtonColor?: string;
  colorsTextColor?: string;
  mode?: "Week" | "Month" | "Quarter" | "Year" | "Custom";
  rangeMaxOffset?: number;
  styleBorderRadius?: string;
  typographyButtonNumberSize?: string;
  typographyDateFontSize?: string;
  typographyFontFamily?: string;
  typographyFontWeight?: string;
};

/**
 * NumberStepper
 *
 * A date-aware stepper. Pick Week/Month/Quarter/Year to auto-calculate dates, or Custom to hide. Outputs data-date (yyyy-MM-dd) and data-value.
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
export function NumberStepper({}: NumberStepperProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <NotSupported _atom={"Code Island"} />
    </div>
  );
}
