/**
 * @generated
 * @file AdrMetric (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";

/**
 * Props for {@link AdrMetric}
 */
export type AdrMetricProps = {
  text1?: React.ReactNode;
  text2?: React.ReactNode;
  text3?: React.ReactNode;
};

/**
 * AdrMetric
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
export function AdrMetric({
  text1 = "ADR",
  text2 = "$0.00",
  text3 = "$0.00",
}: AdrMetricProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={"metric-wrapper is-horizontal is-gap-col_1rem"}
        tag={"div"}
      >
        <Block className={"metric-label is-align-top"} tag={"div"}>
          {text1}
        </Block>
        <Block className={"metric-wrapper"} tag={"div"}>
          <Block className={"metric-value is-currency-2dp"} tag={"div"}>
            {text2}
          </Block>
          <Block className={"metric-value is-currency-2dp is-var"} tag={"div"}>
            {text3}
          </Block>
        </Block>
      </Block>
    </div>
  );
}
