/**
 * @generated
 * @file BudgetHoverCard (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Heading from "./webflow_modules/Basic/components/Heading";
import HFlex from "./webflow_modules/Layout/components/HFlex";
import { MetricType } from "./MetricType";

/**
 * Props for {@link BudgetHoverCard}
 */
export type BudgetHoverCardProps = {
  budgetAdrAbbreviatedMetric?: boolean;
  budgetAdrIconTrendVisibility?: boolean;
  budgetAdrLayout?:
    | "Base"
    | "Stacked 1col"
    | "Stacked 2col"
    | "Horizontal 1row"
    | "Horizontal 2row";
  budgetAdrMetricType?:
    | "Base"
    | "Occupancy"
    | "Rooms"
    | "ADR"
    | "Revenue"
    | "RevPar"
    | "Nights"
    | "Reservations"
    | "Guests";
  budgetAdrVarianceLabelVisibility?: boolean;
  budgetAdrVarianceMetricVisibility?: boolean;
  budgetAdrVarianceType?:
    | "Base"
    | "to book"
    | "%chg"
    | "var"
    | "var STLY"
    | "var PY"
    | "var WOW";
  budgetGrpAdrAbbreviatedMetric?: boolean;
  budgetGrpAdrIconTrendVisibility?: boolean;
  budgetGrpAdrLayout?:
    | "Base"
    | "Stacked 1col"
    | "Stacked 2col"
    | "Horizontal 1row"
    | "Horizontal 2row";
  budgetGrpAdrMetricType?:
    | "Base"
    | "Occupancy"
    | "Rooms"
    | "ADR"
    | "Revenue"
    | "RevPar"
    | "Nights"
    | "Reservations"
    | "Guests";
  budgetGrpAdrVarianceLabelVisibility?: boolean;
  budgetGrpAdrVarianceMetricVisibility?: boolean;
  budgetGrpAdrVarianceType?:
    | "Base"
    | "to book"
    | "%chg"
    | "var"
    | "var STLY"
    | "var PY"
    | "var WOW";
  budgetGrpOccpAbbreviatedMetric?: boolean;
  budgetGrpOccpIconTrendVisibility?: boolean;
  budgetGrpOccpLayout?:
    | "Base"
    | "Stacked 1col"
    | "Stacked 2col"
    | "Horizontal 1row"
    | "Horizontal 2row";
  budgetGrpOccpMetricType?:
    | "Base"
    | "Occupancy"
    | "Rooms"
    | "ADR"
    | "Revenue"
    | "RevPar"
    | "Nights"
    | "Reservations"
    | "Guests";
  budgetGrpOccpVarianceLabelVisibility?: boolean;
  budgetGrpOccpVarianceMetricVisibility?: boolean;
  budgetGrpOccpVarianceType?:
    | "Base"
    | "to book"
    | "%chg"
    | "var"
    | "var STLY"
    | "var PY"
    | "var WOW";
  budgetGrpRevenueAbbreviatedMetric?: boolean;
  budgetGrpRevenueIconTrendVisibility?: boolean;
  budgetGrpRevenueLayout?:
    | "Base"
    | "Stacked 1col"
    | "Stacked 2col"
    | "Horizontal 1row"
    | "Horizontal 2row";
  budgetGrpRevenueMetricType?:
    | "Base"
    | "Occupancy"
    | "Rooms"
    | "ADR"
    | "Revenue"
    | "RevPar"
    | "Nights"
    | "Reservations"
    | "Guests";
  budgetGrpRevenueVarianceLabelVisibility?: boolean;
  budgetGrpRevenueVarianceMetricVisibility?: boolean;
  budgetGrpRevenueVarianceType?:
    | "Base"
    | "to book"
    | "%chg"
    | "var"
    | "var STLY"
    | "var PY"
    | "var WOW";
  budgetOccpAbbreviatedMetric?: boolean;
  budgetOccpIconTrendVisibility?: boolean;
  budgetOccpLayout?:
    | "Base"
    | "Stacked 1col"
    | "Stacked 2col"
    | "Horizontal 1row"
    | "Horizontal 2row";
  budgetOccpMetricType?:
    | "Base"
    | "Occupancy"
    | "Rooms"
    | "ADR"
    | "Revenue"
    | "RevPar"
    | "Nights"
    | "Reservations"
    | "Guests";
  budgetOccpVarianceLabelVisibility?: boolean;
  budgetOccpVarianceMetricVisibility?: boolean;
  budgetOccpVarianceType?:
    | "Base"
    | "to book"
    | "%chg"
    | "var"
    | "var STLY"
    | "var PY"
    | "var WOW";
  budgetRevParAbbreviatedMetric?: boolean;
  budgetRevParIconTrendVisibility?: boolean;
  budgetRevParLayout?:
    | "Base"
    | "Stacked 1col"
    | "Stacked 2col"
    | "Horizontal 1row"
    | "Horizontal 2row";
  budgetRevParMetricType?:
    | "Base"
    | "Occupancy"
    | "Rooms"
    | "ADR"
    | "Revenue"
    | "RevPar"
    | "Nights"
    | "Reservations"
    | "Guests";
  budgetRevParVarianceLabelVisibility?: boolean;
  budgetRevParVarianceMetricVisibility?: boolean;
  budgetRevParVarianceType?:
    | "Base"
    | "to book"
    | "%chg"
    | "var"
    | "var STLY"
    | "var PY"
    | "var WOW";
  budgetTrnAdrAbbreviatedMetric?: boolean;
  budgetTrnAdrIconTrendVisibility?: boolean;
  budgetTrnAdrLayout?:
    | "Base"
    | "Stacked 1col"
    | "Stacked 2col"
    | "Horizontal 1row"
    | "Horizontal 2row";
  budgetTrnAdrMetricType?:
    | "Base"
    | "Occupancy"
    | "Rooms"
    | "ADR"
    | "Revenue"
    | "RevPar"
    | "Nights"
    | "Reservations"
    | "Guests";
  budgetTrnAdrVarianceLabelVisibility?: boolean;
  budgetTrnAdrVarianceMetricVisibility?: boolean;
  budgetTrnAdrVarianceType?:
    | "Base"
    | "to book"
    | "%chg"
    | "var"
    | "var STLY"
    | "var PY"
    | "var WOW";
  budgetTrnOccpAbbreviatedMetric?: boolean;
  budgetTrnOccpIconTrendVisibility?: boolean;
  budgetTrnOccpLayout?:
    | "Base"
    | "Stacked 1col"
    | "Stacked 2col"
    | "Horizontal 1row"
    | "Horizontal 2row";
  budgetTrnOccpMetricType?:
    | "Base"
    | "Occupancy"
    | "Rooms"
    | "ADR"
    | "Revenue"
    | "RevPar"
    | "Nights"
    | "Reservations"
    | "Guests";
  budgetTrnOccpVarianceLabelVisibility?: boolean;
  budgetTrnOccpVarianceMetricVisibility?: boolean;
  budgetTrnOccpVarianceType?:
    | "Base"
    | "to book"
    | "%chg"
    | "var"
    | "var STLY"
    | "var PY"
    | "var WOW";
  budgetTrnRevenueAbbreviatedMetric?: boolean;
  budgetTrnRevenueIconTrendVisibility?: boolean;
  budgetTrnRevenueLayout?:
    | "Base"
    | "Stacked 1col"
    | "Stacked 2col"
    | "Horizontal 1row"
    | "Horizontal 2row";
  budgetTrnRevenueMetricType?:
    | "Base"
    | "Occupancy"
    | "Rooms"
    | "ADR"
    | "Revenue"
    | "RevPar"
    | "Nights"
    | "Reservations"
    | "Guests";
  budgetTrnRevenueVarianceLabelVisibility?: boolean;
  budgetTrnRevenueVarianceMetricVisibility?: boolean;
  budgetTrnRevenueVarianceType?:
    | "Base"
    | "to book"
    | "%chg"
    | "var"
    | "var STLY"
    | "var PY"
    | "var WOW";
};

/**
 * BudgetHoverCard
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
export function BudgetHoverCard({
  budgetAdrAbbreviatedMetric = false,
  budgetAdrIconTrendVisibility = true,
  budgetAdrLayout = "Horizontal 1row",
  budgetAdrMetricType = "ADR",
  budgetAdrVarianceLabelVisibility = true,
  budgetAdrVarianceMetricVisibility = true,
  budgetAdrVarianceType = "to book",
  budgetGrpAdrAbbreviatedMetric = false,
  budgetGrpAdrIconTrendVisibility = true,
  budgetGrpAdrLayout = "Base",
  budgetGrpAdrMetricType = "ADR",
  budgetGrpAdrVarianceLabelVisibility = true,
  budgetGrpAdrVarianceMetricVisibility = true,
  budgetGrpAdrVarianceType = "var",
  budgetGrpOccpAbbreviatedMetric = false,
  budgetGrpOccpIconTrendVisibility = true,
  budgetGrpOccpLayout = "Base",
  budgetGrpOccpMetricType = "Occupancy",
  budgetGrpOccpVarianceLabelVisibility = true,
  budgetGrpOccpVarianceMetricVisibility = true,
  budgetGrpOccpVarianceType = "var",
  budgetGrpRevenueAbbreviatedMetric = false,
  budgetGrpRevenueIconTrendVisibility = true,
  budgetGrpRevenueLayout = "Base",
  budgetGrpRevenueMetricType = "Revenue",
  budgetGrpRevenueVarianceLabelVisibility = true,
  budgetGrpRevenueVarianceMetricVisibility = true,
  budgetGrpRevenueVarianceType = "var",
  budgetOccpAbbreviatedMetric = false,
  budgetOccpIconTrendVisibility = true,
  budgetOccpLayout = "Horizontal 1row",
  budgetOccpMetricType = "Occupancy",
  budgetOccpVarianceLabelVisibility = true,
  budgetOccpVarianceMetricVisibility = true,
  budgetOccpVarianceType = "to book",
  budgetRevParAbbreviatedMetric = false,
  budgetRevParIconTrendVisibility = true,
  budgetRevParLayout = "Horizontal 1row",
  budgetRevParMetricType = "Revenue",
  budgetRevParVarianceLabelVisibility = true,
  budgetRevParVarianceMetricVisibility = true,
  budgetRevParVarianceType = "to book",
  budgetTrnAdrAbbreviatedMetric = false,
  budgetTrnAdrIconTrendVisibility = true,
  budgetTrnAdrLayout = "Base",
  budgetTrnAdrMetricType = "ADR",
  budgetTrnAdrVarianceLabelVisibility = true,
  budgetTrnAdrVarianceMetricVisibility = true,
  budgetTrnAdrVarianceType = "var",
  budgetTrnOccpAbbreviatedMetric = false,
  budgetTrnOccpIconTrendVisibility = true,
  budgetTrnOccpLayout = "Base",
  budgetTrnOccpMetricType = "Occupancy",
  budgetTrnOccpVarianceLabelVisibility = true,
  budgetTrnOccpVarianceMetricVisibility = true,
  budgetTrnOccpVarianceType = "var",
  budgetTrnRevenueAbbreviatedMetric = false,
  budgetTrnRevenueIconTrendVisibility = true,
  budgetTrnRevenueLayout = "Base",
  budgetTrnRevenueMetricType = "Revenue",
  budgetTrnRevenueVarianceLabelVisibility = true,
  budgetTrnRevenueVarianceMetricVisibility = true,
  budgetTrnRevenueVarianceType = "var",
}: BudgetHoverCardProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={"card add-shadow bg-color-light-1 text-color-primary"}
        tag={"div"}
      >
        <Block className={"card-body bg-color-light-1"} tag={"div"}>
          <HFlex
            className={
              "flex-block is-stacked is-max-height is-gap-row_1rem padding-xs"
            }
            tag={"div"}
          >
            <Heading className={"metric-headline is-underline"} tag={"h1"}>
              {"Budget Reach"}
            </Heading>
            <MetricType
              abbreviatedMetric={budgetOccpAbbreviatedMetric}
              iconTrendVisibility={budgetOccpIconTrendVisibility}
              layout={budgetOccpLayout}
              metricType={budgetOccpMetricType}
              varianceLabelVisibility={budgetOccpVarianceLabelVisibility}
              varianceMetricVisibility={budgetOccpVarianceMetricVisibility}
              varianceType={budgetOccpVarianceType}
            />
            <MetricType
              abbreviatedMetric={budgetAdrAbbreviatedMetric}
              iconTrendVisibility={budgetAdrIconTrendVisibility}
              layout={budgetAdrLayout}
              metricType={budgetAdrMetricType}
              varianceLabelVisibility={budgetAdrVarianceLabelVisibility}
              varianceMetricVisibility={budgetAdrVarianceMetricVisibility}
              varianceType={budgetAdrVarianceType}
            />
            <MetricType
              abbreviatedMetric={budgetRevParAbbreviatedMetric}
              iconTrendVisibility={budgetRevParIconTrendVisibility}
              layout={budgetRevParLayout}
              metricType={budgetRevParMetricType}
              varianceLabelVisibility={budgetRevParVarianceLabelVisibility}
              varianceMetricVisibility={budgetRevParVarianceMetricVisibility}
              varianceType={budgetRevParVarianceType}
            />
          </HFlex>
          <Block className={"inline-flex"} tag={"div"}>
            <HFlex className={"flex-block is-stacked padding-xs"} tag={"div"}>
              <Heading
                className={"metric-headline is-secondary is-underline"}
                tag={"h1"}
              >
                {"Transient"}
              </Heading>
              <MetricType
                abbreviatedMetric={budgetTrnOccpAbbreviatedMetric}
                iconTrendVisibility={budgetTrnOccpIconTrendVisibility}
                layout={budgetTrnOccpLayout}
                metricType={budgetTrnOccpMetricType}
                varianceLabelVisibility={budgetTrnOccpVarianceLabelVisibility}
                varianceMetricVisibility={budgetTrnOccpVarianceMetricVisibility}
                varianceType={budgetTrnOccpVarianceType}
              />
              <MetricType
                abbreviatedMetric={budgetTrnAdrAbbreviatedMetric}
                iconTrendVisibility={budgetTrnAdrIconTrendVisibility}
                layout={budgetTrnAdrLayout}
                metricType={budgetTrnAdrMetricType}
                varianceLabelVisibility={budgetTrnAdrVarianceLabelVisibility}
                varianceMetricVisibility={budgetTrnAdrVarianceMetricVisibility}
                varianceType={budgetTrnAdrVarianceType}
              />
              <MetricType
                abbreviatedMetric={budgetTrnRevenueAbbreviatedMetric}
                iconTrendVisibility={budgetTrnRevenueIconTrendVisibility}
                layout={budgetTrnRevenueLayout}
                metricType={budgetTrnRevenueMetricType}
                varianceLabelVisibility={
                  budgetTrnRevenueVarianceLabelVisibility
                }
                varianceMetricVisibility={
                  budgetTrnRevenueVarianceMetricVisibility
                }
                varianceType={budgetTrnRevenueVarianceType}
              />
            </HFlex>
            <HFlex className={"flex-block is-stacked padding-xs"} tag={"div"}>
              <Heading
                className={"metric-headline is-secondary is-underline"}
                tag={"h1"}
              >
                {"Group"}
              </Heading>
              <MetricType
                abbreviatedMetric={budgetGrpOccpAbbreviatedMetric}
                iconTrendVisibility={budgetGrpOccpIconTrendVisibility}
                layout={budgetGrpOccpLayout}
                metricType={budgetGrpOccpMetricType}
                varianceLabelVisibility={budgetGrpOccpVarianceLabelVisibility}
                varianceMetricVisibility={budgetGrpOccpVarianceMetricVisibility}
                varianceType={budgetGrpOccpVarianceType}
              />
              <MetricType
                abbreviatedMetric={budgetGrpAdrAbbreviatedMetric}
                iconTrendVisibility={budgetGrpAdrIconTrendVisibility}
                layout={budgetGrpAdrLayout}
                metricType={budgetGrpAdrMetricType}
                varianceLabelVisibility={budgetGrpAdrVarianceLabelVisibility}
                varianceMetricVisibility={budgetGrpAdrVarianceMetricVisibility}
                varianceType={budgetGrpAdrVarianceType}
              />
              <MetricType
                abbreviatedMetric={budgetGrpRevenueAbbreviatedMetric}
                iconTrendVisibility={budgetGrpRevenueIconTrendVisibility}
                layout={budgetGrpRevenueLayout}
                metricType={budgetGrpRevenueMetricType}
                varianceLabelVisibility={
                  budgetGrpRevenueVarianceLabelVisibility
                }
                varianceMetricVisibility={
                  budgetGrpRevenueVarianceMetricVisibility
                }
                varianceType={budgetGrpRevenueVarianceType}
              />
            </HFlex>
          </Block>
        </Block>
      </Block>
    </div>
  );
}
