/**
 * @generated
 * @file ChartByDayMix (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";

/**
 * Props for {@link ChartByDayMix}
 */
export type ChartByDayMixProps = {
  chartTitle?: React.ReactNode;
  horizontalAxis?: React.ReactNode;
  stackedBarChartSlot?: React.ReactNode;
  text1?: React.ReactNode;
  text2?: React.ReactNode;
};

/**
 * ChartByDayMix
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
export function ChartByDayMix({
  chartTitle = "TRANSIENTVSGROUP OTB BYDAY",
  horizontalAxis,
  stackedBarChartSlot,
  text1 = "capactity",
  text2 = "0102030405060708 091011121314151617 1819202122232425 2627282930",
}: ChartByDayMixProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"bar-mix-card add-shadow"} tag={"div"}>
        <Block className={"bar-mix-card_plot-area"} tag={"div"}>
          <Block className={"chart-container"} tag={"div"}>
            {stackedBarChartSlot}
            {horizontalAxis}
          </Block>
        </Block>
        <Block className={"flex_vertical"} tag={"div"}>
          <Block className={"kpi-card_label is-secondary"} tag={"div"}>
            {chartTitle}
          </Block>
        </Block>
      </Block>
    </div>
  );
}
