/**
 * @generated
 * @file KpiCard (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import BlockContainer from "./webflow_modules/Layout/components/BlockContainer";
import Heading from "./webflow_modules/Basic/components/Heading";
import HFlex from "./webflow_modules/Layout/components/HFlex";
import VFlex from "./webflow_modules/Layout/components/VFlex";

/**
 * Props for {@link KpiCard}
 */
export type KpiCardProps = {
  /** Donut chart the includes a fill for current revenue OTB with the full amount as the total budget. In the center of the donut, it should include two row, the first with the total revenue remaining to book in order to reach budget with the label underneath.*/
  chart1DonutChartRuntimeProps?: Record<string, unknown>;
  /** This is a multi-layer concentric radial donut chart composed of three circular progress rings centered around a KPI label. Three equally centered donut rings stacked concentrically. Hollow center used as a metric callout.*/
  chart1DonutChartSlot?: React.ReactNode;
  chart2HorizontalBarChartRuntimeProps?: Record<string, unknown>;
  /** a vertical bar chart representing each day of the month. The Bar representing the budget revenue for the day with the fill represents revenue on the books revenue with a hover card that show the detailed revenue amounts.*/
  chart2HorizontalBarChartSlot?: React.ReactNode;
  /** Current Occupancy Variance to Budget. Format +/- 0.0%*/
  metric1MetricVarRuntimeProps?: Record<string, unknown>;
  /** Current Occupancy On the Books. . Format 0.0%*/
  metric1SubMetricRuntimeProps?: Record<string, unknown>;
  metric1SubMetricSlot?: React.ReactNode;
  metric1SubMetricVarSlot?: React.ReactNode;
  /** Insert the up arrow when positive or down arrow when negative.

    vars:
    var(--_apps---charts--positive)

    var(--_apps---charts--negative)

    icon:
    <FoundationIcon name="fi-arrow-up" | fi-arrow-down/>*/
  metric1VarianceIconSlot?: React.ReactNode;
  /** Current Rooms On the Books*/
  metric2SubMetricRuntimeProps?: Record<string, unknown>;
  metric2SubMetricSlot?: React.ReactNode;
  /** Current Rooms Variance to Budget. Format +/- $0*/
  metric2SubMetricVarRuntimeProps?: Record<string, unknown>;
  metric2SubMetricVarSlot?: React.ReactNode;
  /** Insert the up arrow when positive or down arrow when negative.

    vars:
    var(--_apps---charts--positive)

    var(--_apps---charts--negative)

    icon:
    <FoundationIcon name="fi-arrow-up" | fi-arrow-down/>*/
  metric2VarianceIconSlot?: React.ReactNode;
  /** Current ADR On the Books. Format $0.00*/
  metric3SubMetricRuntimeProps?: Record<string, unknown>;
  metric3SubMetricSlot?: React.ReactNode;
  /** Current ADR Variance to Budget Format +/- $0.00*/
  metric3SubMetricVarRuntimeProps?: Record<string, unknown>;
  metric3SubMetricVarSlot?: React.ReactNode;
  /** Insert the up arrow when positive or down arrow when negative.

    vars:
    var(--_apps---charts--positive)

    var(--_apps---charts--negative)

    icon:
    <FoundationIcon name="fi-arrow-up" | fi-arrow-down/>*/
  metric3VarianceIconSlot?: React.ReactNode;
  /** Current REVPAR On the Books. Format $0.00*/
  metric4SubMetricRuntimeProps?: Record<string, unknown>;
  metric4SubMetricSlot?: React.ReactNode;
  /** Current REVPAR Variance to Budget Format +/- $0.00*/
  metric4SubMetricVarRuntimeProps?: Record<string, unknown>;
  metric4SubMetricVarSlot?: React.ReactNode;
  /** Insert the up arrow when positive or down arrow when negative.

    vars:
    var(--_apps---charts--positive)

    var(--_apps---charts--negative)

    icon:
    <FoundationIcon name="fi-arrow-up" | fi-arrow-down/>*/
  metric4VarianceIconSlot?: React.ReactNode;
  /** Insert the up arrow when positive or down arrow when negative.

    vars:
    var(--_apps---charts--positive)

    var(--_apps---charts--negative)

    icon:
    <FoundationIcon name="fi-arrow-up" | fi-arrow-down/>*/
  primaryMetricArrowIconSlot?: React.ReactNode;
  /** Current Revenue On the Books. Format $0*/
  primaryMetricPrimaryMetricRuntimeProps?: Record<string, unknown>;
  primaryMetricPrimaryMetricSlot?: React.ReactNode;
  /** Current Revenue Variance to Budget. Format +/- $0*/
  primaryMetricPrimaryMetricVarRuntimeProps?: Record<string, unknown>;
  primaryMetricPrimaryMetricVarSlot?: React.ReactNode;
  /** Insert the up arrow when positive or down arrow when negative.

    vars:
    var(--_apps---charts--positive)

    var(--_apps---charts--negative)

    icon:
    <FoundationIcon name="fi-arrow-up" | fi-arrow-down/>*/
  primaryMetricVarianceIconSlot?: React.ReactNode;
};

/**
 * KpiCard
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
export function KpiCard({
  chart1DonutChartRuntimeProps = {},
  chart1DonutChartSlot = "",
  chart2HorizontalBarChartRuntimeProps = {},
  chart2HorizontalBarChartSlot = "",
  metric1MetricVarRuntimeProps = {},
  metric1SubMetricRuntimeProps = {},
  metric1SubMetricSlot = "",
  metric1SubMetricVarSlot = "",
  metric1VarianceIconSlot = "",
  metric2SubMetricRuntimeProps = {},
  metric2SubMetricSlot = "",
  metric2SubMetricVarRuntimeProps = {},
  metric2SubMetricVarSlot = "",
  metric2VarianceIconSlot = "",
  metric3SubMetricRuntimeProps = {},
  metric3SubMetricSlot = "",
  metric3SubMetricVarRuntimeProps = {},
  metric3SubMetricVarSlot = "",
  metric3VarianceIconSlot = "",
  metric4SubMetricRuntimeProps = {},
  metric4SubMetricSlot = "",
  metric4SubMetricVarRuntimeProps = {},
  metric4SubMetricVarSlot = "",
  metric4VarianceIconSlot = "",
  primaryMetricArrowIconSlot = "",
  primaryMetricPrimaryMetricRuntimeProps = {},
  primaryMetricPrimaryMetricSlot = "",
  primaryMetricPrimaryMetricVarRuntimeProps = {},
  primaryMetricPrimaryMetricVarSlot = "",
  primaryMetricVarianceIconSlot = "",
}: KpiCardProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <BlockContainer
        className={"metric-container"}
        grid={{
          type: "container",
        }}
        tag={"div"}
      >
        <HFlex className={"kpi-card add-shadow"} tag={"div"}>
          <VFlex className={"kpi-card_left"} tag={"div"}>
            <HFlex className={"kpi-card_top"} tag={"div"}>
              <Block className={"kpi-card_sub-metric"} tag={"div"}>
                <Block className={"kpi-card_label is-secondary"} tag={"div"}>
                  {"Occp"}
                  <br />
                </Block>
                <Block className={"kpi-card_metric-wrapper"} tag={"div"}>
                  <Block
                    className={"kpi-card_metric is-secondary"}
                    tag={"div"}
                    {...metric1SubMetricRuntimeProps}
                  >
                    {metric1SubMetricSlot ?? "$0"}
                  </Block>
                  <Block className={"kpi-card_var-wrapper"} tag={"div"}>
                    <Block
                      className={"kpi-card_delta"}
                      tag={"div"}
                      {...metric1MetricVarRuntimeProps}
                    >
                      {metric1SubMetricVarSlot ?? "$0"}
                    </Block>
                    <Block className={"arrow-icon"} tag={"div"}>
                      {metric1VarianceIconSlot}
                    </Block>
                  </Block>
                </Block>
              </Block>
              <Block className={"kpi-card_sub-metric"} tag={"div"}>
                <Block className={"kpi-card_label is-secondary"} tag={"div"}>
                  {"Rooms"}
                </Block>
                <Block className={"kpi-card_metric-wrapper"} tag={"div"}>
                  <Block
                    className={"kpi-card_metric is-secondary"}
                    tag={"div"}
                    {...metric2SubMetricRuntimeProps}
                  >
                    {metric2SubMetricSlot ?? "$0"}
                  </Block>
                  <Block className={"kpi-card_var-wrapper"} tag={"div"}>
                    <Block
                      className={"kpi-card_delta"}
                      tag={"div"}
                      {...metric2SubMetricVarRuntimeProps}
                    >
                      {metric2SubMetricVarSlot ?? "$0"}
                    </Block>
                    <Block className={"arrow-icon"} tag={"div"}>
                      {metric2VarianceIconSlot}
                    </Block>
                  </Block>
                </Block>
              </Block>
            </HFlex>
            <Block className={"kpi-card_middle"} tag={"div"}>
              <Block className={"kpi-card_primary-metric"} tag={"div"}>
                <VFlex className={"flex-block"} tag={"div"}>
                  <Heading className={"kpi-card_label is-primary"} tag={"h1"}>
                    {"Budget"}
                  </Heading>
                </VFlex>
                <Block className={"kpi-card_metric-wrapper"} tag={"div"}>
                  <Block
                    className={"kpi-card_metric is-primary"}
                    tag={"div"}
                    {...primaryMetricPrimaryMetricRuntimeProps}
                  >
                    {primaryMetricPrimaryMetricSlot ?? "$0"}
                  </Block>
                  <Block className={"kpi-card_var-wrapper"} tag={"div"}>
                    <Block
                      className={"kpi-card_delta"}
                      tag={"div"}
                      {...primaryMetricPrimaryMetricVarRuntimeProps}
                    >
                      {primaryMetricPrimaryMetricVarSlot ?? "+/- $0"}
                    </Block>
                    <Block className={"arrow-icon"} tag={"div"}>
                      {primaryMetricVarianceIconSlot}
                    </Block>
                  </Block>
                </Block>
              </Block>
            </Block>
            <HFlex className={"kpi-card_bottom"} tag={"div"}>
              <Block className={"kpi-card_sub-metric"} tag={"div"}>
                <Block className={"kpi-card_label is-secondary"} tag={"div"}>
                  {"ADR"}
                </Block>
                <Block className={"kpi-card_metric-wrapper"} tag={"div"}>
                  <Block
                    className={"kpi-card_metric is-secondary"}
                    tag={"div"}
                    {...metric3SubMetricRuntimeProps}
                  >
                    {metric3SubMetricSlot ?? "$0"}
                  </Block>
                  <Block className={"kpi-card_var-wrapper"} tag={"div"}>
                    <Block
                      className={"kpi-card_delta"}
                      tag={"div"}
                      {...metric3SubMetricVarRuntimeProps}
                    >
                      {metric3SubMetricVarSlot ?? "$0"}
                    </Block>
                    <Block className={"arrow-icon"} tag={"div"}>
                      {metric3VarianceIconSlot}
                    </Block>
                  </Block>
                </Block>
              </Block>
              <Block className={"kpi-card_sub-metric"} tag={"div"}>
                <Block className={"kpi-card_label is-secondary"} tag={"div"}>
                  {"REVPAR"}
                </Block>
                <Block className={"kpi-card_metric-wrapper"} tag={"div"}>
                  <Block
                    className={"kpi-card_metric is-secondary"}
                    tag={"div"}
                    {...metric4SubMetricRuntimeProps}
                  >
                    {metric4SubMetricSlot ?? "$0"}
                  </Block>
                  <Block className={"kpi-card_var-wrapper"} tag={"div"}>
                    <Block
                      className={"kpi-card_delta"}
                      tag={"div"}
                      {...metric4SubMetricVarRuntimeProps}
                    >
                      {metric4SubMetricVarSlot ?? "$0"}
                    </Block>
                    <Block className={"arrow-icon"} tag={"div"}>
                      {metric4VarianceIconSlot}
                    </Block>
                  </Block>
                </Block>
              </Block>
            </HFlex>
          </VFlex>
          <VFlex className={"kpi-card_right"} tag={"div"}>
            <Block className={"kpi-card_chart-wrapper is-chart-1"} tag={"div"}>
              <Block
                className={"kpi-card_chart is-donut-chart"}
                tag={"div"}
                {...chart1DonutChartRuntimeProps}
              >
                {chart1DonutChartSlot}
              </Block>
            </Block>
            <Block className={"kpi-card_chart-wrapper is-chart-2"} tag={"div"}>
              <Block
                className={"kpi-card_chart is-bar-chart"}
                tag={"div"}
                {...chart2HorizontalBarChartRuntimeProps}
              >
                {chart2HorizontalBarChartSlot}
              </Block>
            </Block>
          </VFlex>
        </HFlex>
        <Block className={"variable-classes"} tag={"div"}>
          <Block className={"is-positive"} tag={"div"} />
          <Block className={"is-negative"} tag={"div"} />
        </Block>
      </BlockContainer>
    </div>
  );
}
