/**
 * @generated
 * @file PageTraffic (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Heading from "./webflow_modules/Basic/components/Heading";
import HtmlEmbed from "./webflow_modules/Embed/components/HtmlEmbed";

/**
 * Props for {@link PageTraffic}
 */
export type PageTrafficProps = {
  text1?: React.ReactNode;
  text2?: React.ReactNode;
  text3?: React.ReactNode;
  text4?: React.ReactNode;
  text5?: React.ReactNode;
  text6?: React.ReactNode;
  title?: React.ReactNode;
};

/**
 * PageTraffic
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
export function PageTraffic({
  text1 = "8,749",
  text2 = "48%",
  text3 = "Impressions",
  text4 = "592",
  text5 = "16%",
  text6 = "Unique Page Visitors",
  title = "Page Traffic",
}: PageTrafficProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"page-traffic-card add-shadow"} tag={"div"}>
        <Block className={"page-traffic_card-label-wrapper"} tag={"div"}>
          <Heading className={"page-traffic_card_label"} tag={"h1"}>
            {title}
          </Heading>
          <Block className={"icon-wrapper"} tag={"div"}>
            <HtmlEmbed
              className={"chevron-right-arrow"}
              content={""}
              value={
                "%3Csvg%20%20viewBox%3D%220%200%2024%2024%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cpath%20fill%3D%22none%22%20d%3D%22M0%200h24v24H0V0Z%22%2F%3E%3Cpath%20fill%3D%22currentColor%22%20d%3D%22M10%206L8.59%207.41%2013.17%2012l-4.58%204.59L10%2018l6-6%20-6-6Z%22%2F%3E%3C%2Fsvg%3E"
              }
            />
          </Block>
        </Block>
        <Block className={"page-traffic_metrics-container"} tag={"div"}>
          <Block className={"page-traffic_metric-padding"} tag={"div"}>
            <Block className={"page-traffic_metirc-block-padding"} tag={"div"}>
              <Block
                className={"page-traffic_primary-metric-wrapper"}
                tag={"div"}
              >
                <Block className={"page-traffic_primary-metric"} tag={"div"}>
                  {text1}
                </Block>
              </Block>
              <Block className={"page-traffic_var-metric-wrapper"} tag={"div"}>
                <Block
                  className={"icon-wrapper-circle is-positive"}
                  tag={"div"}
                >
                  <HtmlEmbed
                    className={"arrow-icon"}
                    content={""}
                    value={
                      "%3Csvg%20viewBox%3D%220%200%20100%20100%22%20fill%3D%22currentColor%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cpath%20d%3D%22M78.016%2049.132L51.961%2012.714c-.471-.66-1.233-1.049-2.043-1.051%20-.006%200-.006%200-.006%200%20-.815.002-1.575.396-2.048%201.059L21.977%2049.14c-.546.767-.616%201.776-.183%202.612%20.426.835%201.292%201.361%202.236%201.361h12.183l-.001%2032.709c0%201.39%201.125%202.515%202.516%202.515l22.541-.001c1.389.001%202.515-1.124%202.516-2.517V53.114h12.187c.94%200%201.803-.53%202.237-1.367%20.432-.836.357-1.847-.193-2.615Z%22%2F%3E%3C%2Fsvg%3E"
                    }
                  />
                </Block>
                <Block
                  className={"page-traffic_variance-metric is-positive"}
                  tag={"div"}
                >
                  {text2}
                </Block>
              </Block>
            </Block>
            <Block className={"kpi-card_label is-secondary-font"} tag={"div"}>
              {text3}
            </Block>
          </Block>
          <Block className={"page-traffic_metric-padding"} tag={"div"}>
            <Block className={"page-traffic_metirc-block-padding"} tag={"div"}>
              <Block
                className={"page-traffic_primary-metric-wrapper"}
                tag={"div"}
              >
                <Block className={"page-traffic_primary-metric"} tag={"div"}>
                  {text4}
                </Block>
              </Block>
              <Block className={"page-traffic_var-metric-wrapper"} tag={"div"}>
                <Block
                  className={"icon-wrapper-circle is-negative"}
                  tag={"div"}
                >
                  <HtmlEmbed
                    className={"arrow-icon"}
                    content={""}
                    value={
                      "%3Csvg%20viewBox%3D%220%200%20100%20100%22%20fill%3D%22currentColor%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cpath%20d%3D%22M78.016%2049.132L51.961%2012.714c-.471-.66-1.233-1.049-2.043-1.051%20-.006%200-.006%200-.006%200%20-.815.002-1.575.396-2.048%201.059L21.977%2049.14c-.546.767-.616%201.776-.183%202.612%20.426.835%201.292%201.361%202.236%201.361h12.183l-.001%2032.709c0%201.39%201.125%202.515%202.516%202.515l22.541-.001c1.389.001%202.515-1.124%202.516-2.517V53.114h12.187c.94%200%201.803-.53%202.237-1.367%20.432-.836.357-1.847-.193-2.615Z%22%2F%3E%3C%2Fsvg%3E"
                    }
                  />
                </Block>
                <Block className={"page-traffic_variance-metric"} tag={"div"}>
                  {text5}
                </Block>
              </Block>
            </Block>
            <Block className={"kpi-card_label is-secondary-font"} tag={"div"}>
              {text6}
            </Block>
          </Block>
        </Block>
      </Block>
    </div>
  );
}
