/**
 * @generated
 * @file PerformanceCardToolTip (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Heading from "./webflow_modules/Basic/components/Heading";
import { MetricType } from "./MetricType";

/**
 * Props for {@link PerformanceCardToolTip}
 */
export type PerformanceCardToolTipProps = {
  /** Displays the ADR Variance to Budget 
    Var = Budget ADR - OTB -ADR
    $0.00*/
  adrAdrVarBudgetRuntimeProps?: Record<string, unknown>;
  /** Displays the ADR Variance to Budget 
    Var = Budget ADR - OTB -ADR
    $0.00*/
  adrAdrVarBudgetSlot?: React.ReactNode;
  /** $0.00*/
  adrTotalAdrotbRuntimeProps?: Record<string, unknown>;
  /** $0.00*/
  adrTotalAdrotbSlot?: React.ReactNode;
  adrTrnTotalAdrotbRuntimeProps?: Record<string, unknown>;
  adrTrnTotalAdrotbSlot?: React.ReactNode;
  revenueRevenueVarBudgetSlot?: Record<string, unknown>;
  /** Displays the Revenue Variance to Budget 
    Var = Budget Revenue - OTB Revenue*/
  revenueRevenueVarBudgetSlot2?: React.ReactNode;
  /** Displays the Revenue Variance to Budget 
    Var = Budget Revenue - OTB Revenue*/
  revenueTrnRevenueVarBudgetRuntimeProps?: React.ReactNode;
  /** Displays the Revenue Variance to Budget 
    Var = Budget Revenue - OTB Revenue*/
  revenueTrnRevenueVarBudgetSlot?: Record<string, unknown>;
  /** Total Revenue OTB
    $0 No Decimal*/
  revenueTrnTotalRevenueOtbMetricSlot?: React.ReactNode;
  /** Total Revenue OTB
    $0 No Decimal*/
  revenueTrnTotalRevenueOtbRuntimeProps?: Record<string, unknown>;
  roomsRoomsVarBudgetRuntimeProps?: Record<string, unknown>;
  /** Displays the Revenue Variance to Rooms 
    Var = Budget Rooms - OTB Rooms*/
  roomsRoomsVarBudgetSlot?: React.ReactNode;
  /** Total Rooms OTB*/
  roomsTotalRoomsOtbRuntimeProps?: Record<string, unknown>;
  /** Total Rooms OTB*/
  roomsTotalRoomsOtbSlot?: React.ReactNode;
  roomsTrnTotalRoomsOtbSlot?: React.ReactNode;
  totalRevenueOtbRuntimeProps?: Record<string, unknown>;
  totalRevenueOtbSlot?: React.ReactNode;
  trnTotalRoomsOtbRuntimeProps?: Record<string, unknown>;
};

/**
 * PerformanceCardToolTip
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
export function PerformanceCardToolTip({
  adrAdrVarBudgetRuntimeProps = {},
  adrAdrVarBudgetSlot = "",
  adrTotalAdrotbRuntimeProps = {},
  adrTotalAdrotbSlot = "",
  adrTrnTotalAdrotbRuntimeProps = {},
  adrTrnTotalAdrotbSlot = "",
  revenueRevenueVarBudgetSlot = {},
  revenueRevenueVarBudgetSlot2 = "",
  revenueTrnRevenueVarBudgetRuntimeProps = "",
  revenueTrnRevenueVarBudgetSlot = {},
  revenueTrnTotalRevenueOtbMetricSlot = "",
  revenueTrnTotalRevenueOtbRuntimeProps = {},
  roomsRoomsVarBudgetRuntimeProps = {},
  roomsRoomsVarBudgetSlot = "",
  roomsTotalRoomsOtbRuntimeProps = {},
  roomsTotalRoomsOtbSlot = "",
  roomsTrnTotalRoomsOtbSlot = "",
  totalRevenueOtbRuntimeProps = {},
  totalRevenueOtbSlot = "",
  trnTotalRoomsOtbRuntimeProps = {},
}: PerformanceCardToolTipProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"performance-card_tool-tip-wrapper"} tag={"div"}>
        <Block tag={"div"}>
          <Heading className={"tool-tip_headline is-underline"} tag={"h1"}>
            {"Budget Reach "}
          </Heading>
          <Block className={"tool-tip_wrapper padding-bottom-sm"} tag={"div"}>
            <Block className={"group-wrapper text-color-primary"} tag={"div"}>
              <MetricType layout={"Horizontal 1row"} metricType={"Occupancy"} />
              <MetricType layout={"Horizontal 1row"} metricType={"ADR"} />
              <MetricType
                layout={"Horizontal 1row"}
                metricType={"RevPar"}
                varianceType={"var"}
              />
            </Block>
          </Block>
        </Block>
      </Block>
    </div>
  );
}
